=== nahoc/2017/Production/04_BD/xml/quiz1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 rel. 3 (http://www.altova.com) by Labo (Cegep de Sainte-Foy) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="quiz">
		<xs:annotation>
			<xs:documentation>Un quiz pour tester vos aptitudes à devenir intégrateur(trice) multimédia</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="questions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="question" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="texteQuestion" type="xs:string"/>
										<xs:element name="reponses">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="reponse" minOccurs="4" maxOccurs="4">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="texteReponse">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:enumeration value="jamais"/>
																			<xs:enumeration value="parfois"/>
																			<xs:enumeration value="souvent"/>
																			<xs:enumeration value="toujours"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="pointage" type="xs:integer"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="résultats">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="resultat" maxOccurs="3">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="parametres">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="min" type="xs:integer"/>
													<xs:element name="max" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="commentaire" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nahoc/2017/Production/04_BD/xml/quiz1.xml
<?xml version="1.0" encoding="UTF-8"?>
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz1.xsd">
	<questions>
		<question>
			<texteQuestion>J’aime créer en réponse à des besoins concrets.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>Je cherche à trouver de nouvelles idées et de nouvelles façons de faire.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>J’agis avec méthode, patience et rigueur quand j’ai des problèmes à résoudre.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>Je me sens à l’aise lorsque j’exerce des tâches qui demandent de la minutie ou qui demandent de procéder avec logique.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>J’aime résoudre des problèmes, leur trouver des solutions et prendre des décisions.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>La coopération avec les autres me vient naturellement.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>J'aime travailler en équipe.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>Je prends plaisir à apprendre de nouveaux faits et de nouvelles idées.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>J’aime les outils informatiques et je suis curieux de les connaître.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
		<question>
			<texteQuestion>Je prends plaisir à découvrir différents logiciels par moi-même en suivant les manuels et en effectuant des exercices en ligne.</texteQuestion>
			<reponses>
				<reponse>
					<texteReponse>jamais</texteReponse>
					<pointage>1</pointage>
				</reponse>
				<reponse>
					<texteReponse>parfois</texteReponse>
					<pointage>2</pointage>
				</reponse>
				<reponse>
					<texteReponse>souvent</texteReponse>
					<pointage>4</pointage>
				</reponse>
				<reponse>
					<texteReponse>toujours</texteReponse>
					<pointage>5</pointage>
				</reponse>
			</reponses>
		</question>
	</questions>
	<résultats>
		<resultat>
			<parametres>
				<min>0</min>
				<max>40</max>
			</parametres>
			<commentaire>Vous démontrez peu d’aptitudes nécessaires au travail de l’intégrateur multimédia. Peut-être serait-il sage de consulter votre conseiller en orientation ou en information scolaire et professionnelle afin de savoir quel autre domaine vous conviendrait davantage.</commentaire>
		</resultat>
		<resultat>
			<parametres>
				<min>41</min>
				<max>69</max>
			</parametres>
			<commentaire>Vous démontrez un minimum d’aptitudes nécessaires au travail de l’intégrateur multimédia. Connaissez-vous bien les caractéristiques de la profession et les tâches qui y sont associées? Vous pourriez consulter votre conseiller en orientation ou en information scolaire et professionnelle afin d’en apprendre davantage sur la profession d’intégrateur multimédia.</commentaire>
		</resultat>
		<resultat>
			<parametres>
				<min>70</min>
				<max>100</max>
			</parametres>
			<commentaire>Vous démontrez un maximum d’aptitudes nécessaires au travail de l’intégrateur multimédia. La formation en Techniques d’intégration multimédia semble bien vous correspondre.</commentaire>
		</resultat>
	</résultats>
</quiz>
